# "ported" by Adam Miller <maxamillion@fedoraproject.org> from
#   https://github.com/fedora-cloud/Fedora-Dockerfiles
#
# Originally written for Fedora-Dockerfiles by
#   scollier <scollier@redhat.com>

FROM nginx
MAINTAINER The MSA mini Project <mincloud1501@naver.com>

#ENV LC_ALL en_US.UTF-8

COPY ./index.html /usr/share/nginx/html/

# COPY ./start.sh /
# RUN chmod 755 /start.sh

# ENTRYPOINT ["/xx/sshd","sshd"]
# CMD /start.sh